# Generated by Django 5.2.1 on 2025-06-10 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Usage',
                'verbose_name_plural': 'Voucher Usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
