# Generated by Django 5.2.1 on 2025-06-11 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('voucher', '0002_alter_voucher_options_remove_voucher_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherusage',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='session_duration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.captivesession'),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher'),
        ),
    ]
