# Generated by Django 5.2.1 on 2025-06-11 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_vouchergenerationlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucherusage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher'),
        ),
    ]
