# Generated by Django 5.2.1 on 2025-06-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_alter_voucherusage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='1 day = 1440 minutes'),
        ),
    ]
