# Generated by Django 5.2.1 on 2025-06-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_alter_voucher_duration_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
    ]
