# Generated by Django 5.2.1 on 2025-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captivesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
