# Generated by Django 5.2.1 on 2025-06-18 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_address_business_business_email_and_more'),
        ('portal', '0002_captivesession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='captivesession',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='business.business'),
        ),
    ]
