# Generated by Django 5.2.1 on 2025-06-12 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_voucher_quota'),
        ('payments', '0002_paymenttransaction_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('till_number', models.CharField(max_length=20)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
