# Generated by Django 5.2.1 on 2025-06-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['key'], 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
    ]
