# Generated by Django 5.2.1 on 2025-06-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('routerapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_ip', models.GenericIPAddressField()),
                ('api_port', models.PositiveIntegerField(default=8728)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('interface', models.CharField(help_text='Wireless interface name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='router_config', to='business.business')),
            ],
            options={
                'verbose_name': 'Router Configuration',
                'verbose_name_plural': 'Router Configurations',
            },
        ),
        migrations.DeleteModel(
            name='RouterSession',
        ),
    ]
