# Generated by Django 5.2.1 on 2025-06-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapi', '0003_routerconfig_router_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routerconfig',
            options={'ordering': ['business'], 'verbose_name': 'Router Configuration', 'verbose_name_plural': 'Router Configurations'},
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='interface',
        ),
        migrations.AlterField(
            model_name='routerconfig',
            name='router_type',
            field=models.CharField(choices=[('mikrotik', 'Mikrotik'), ('openwrt', 'OpenWRT'), ('custom', 'Custom')], max_length=100, null=True),
        ),
    ]
