# Generated by Django 5.2.1 on 2025-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapi', '0004_alter_routerconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconfig',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
