# Generated by Django 5.2.1 on 2025-06-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerapi', '0005_routerconfig_created_at_routerconfig_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routerconfig',
            old_name='router_ip',
            new_name='ip_address',
        ),
    ]
