# Generated by Django 5.2.1 on 2025-06-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapi', '0006_rename_router_ip_routerconfig_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
