# Generated by Django 5.2.1 on 2025-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='voucher_quota',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
