# Generated by Django 5.2.1 on 2025-06-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_voucher_quota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name']},
        ),
    ]
